filebeat.prospectors:
- input_type: log
  paths:
    - /Users/ia/Library/EthereumClassic/mainnet/mlogs/geth*
  symlinks: true
  json.message_key: event
  json.keys_under_root: true
output.logstash:
  # hosts: ["localhost:5043"]
  hosts: ["178.62.224.190:5000"]
  # This is will set the index prefix for elasticsearch indices. Important when
  # aggregating logs from multiple machines and instances.
  index: "etcdev-isaac"
